assignment5: main.o Dog.o Fish.o  Horse.o Lizard.o Monkey.o
	g++ -o assignment5 main.o Dog.o Fish.o  Horse.o Lizard.o Monkey.o

main.o: main.cpp
	g++ -c -o main.o main.cpp

Dog.o: Dog.cpp
	g++ -c -o Dog.o Dog.cpp

Fish.o: Fish.cpp
	g++ -c -o Fish.o Fish.cpp


Horse.o: Horse.cpp
	g++ -c -o Horse.o Horse.cpp

Lizard.o: Lizard.cpp
	g++ -c -o Lizard.o Lizard.cpp

Monkey.o: Monkey.cpp
	g++ -c -o Monkey.o Monkey.cpp

clean:
	rm *.o assignment5
